---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-proxy
  namespace: redhat-odh-monitoring
data:
  session_secret: "<prometheus_proxy_secret>"
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-proxy
  namespace: redhat-odh-monitoring
data:
  session_secret: "<alertmanager_proxy_secret>"
type: Opaque
